version: '3.4'

services:

  kafka-cluster:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: kafka-cluster #127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    networks:
    - router-network
  
  emailrequestsrouter:
    image: ${DOCKER_REGISTRY-}emailrequestsrouter
    build:
      context: .
      dockerfile: src/EmailRequestsRouter/Dockerfile
    ports:
    - 5000:5000
    environment: 
    - KAFKACONSUMER__BOOTSTRAPSERVER=kafka-cluster:9092
    - KAFKACONSUMER__TOPICNAME=email-requests
    - KAFKACONSUMER__CONSUMERGROUP=email-requests-router
    
    - KAFKAPRODUCER__BOOTSTRAPSERVER=kafka-cluster:9092
    - KAFKAPRODUCER__VALIDATEDTOPICNAME=validated-email-requests
    - KAFKAPRODUCER__DISQUALIFIEDTOPICNAME=disqualified-email-requests
    volumes:
    - ~/.vsdbg:/remote_debugger:rw
    depends_on:
    - kafka-cluster
    networks:
    - router-network

networks:
  router-network:
    name: router-network